Repository sprint4-part4-team7/TravelPort-49105, pull requests merged in 2024-06, with the labels that each got.

#66 [Ui] 검색 결과 페이지 초안 구현
  src/App.tsx
  src/apis/productAll.ts
  src/apis/review.ts
  src/components/common/headerBar/HeaderBar.tsx
  src/components/common/headerBar/LoginUserHeaderBar.tsx
  src/hooks/reactQuery/product/useProductAllQuery.ts
  src/hooks/reactQuery/querySample.tsx
  src/hooks/reactQuery/review/useReviewAllQuery.ts
  src/hooks/useProductAll.ts
  src/hooks/useProductsWithMinPrice.ts
  src/hooks/useScoreAvg.ts
  src/pages/List.tsx
  src/pages/SearchResultPage.tsx
Labels: 🧾 page, 🎁 component, 📍 api, ✨ enhancement

#67 [Refactor & Fix] 정보 수정, 비밀번호 변경 api 연결 및 토큰 첨부 에러 수정
  src/apis/auth.ts
  src/apis/editInfo.ts
  src/components/myPage/ChangePassword.tsx
  src/components/myPage/EditInfo.tsx
  src/components/myPage/MyPageSideBar.tsx
  src/utils/axios.ts
  src/utils/jwtDecode.ts
  src/utils/zustand.ts
Labels: 🎁 component, 📍 api, ♻️ refactor

#68 [UI] 메인 페이지 UI 구현 완료
  src/assets/icons/arrowleft.svg
  src/assets/icons/arrowright.svg
  src/assets/icons/search-lg.svg
  src/components/Carousel.tsx
  src/components/MainCard.tsx
  src/components/MainCategoryButton.tsx
  src/components/common/SearchBar.tsx
  src/components/common/headerBar/HeaderBar.tsx
  src/components/common/headerBar/LoginUserHeaderBar.tsx
  src/pages/Main.tsx
Labels: 🧾 page, 🎁 component, 💄 style

#69 [Feat] productregist 기본 페이지 구현, Category 기능구현, Category API 연결
  src/App.tsx
  src/apis/category.ts
  src/pages/productRegist/Category.tsx
  src/pages/productRegist/CheckButton.tsx
  src/pages/productRegist/Date.tsx
  src/pages/productRegist/Description.tsx
  src/pages/productRegist/Option.tsx
  src/pages/productRegist/ProductRegist.tsx
Labels: 🧾 page, 📍 api, 💄 style, ✨ enhancement

#70 [Feat] Review 컴포넌트 구현, 관련 API 연결
  src/assets/icons/arrowdown-blue.svg
  src/assets/icons/arrowright-blue.svg
  src/assets/icons/message-smile-square.svg
  src/components/Review.tsx
Labels: 🎁 component, 📍 api, ✨ enhancement

#71 [ Feat ] 검색 결과 페이지 필터링 버튼 기능 구현 완료
  src/apis/review.ts
  src/components/common/headerBar/HeaderBar.tsx
  src/components/common/layout/Layout.tsx
  src/hooks/useProductsWithMinPrice.ts
  src/pages/Main.tsx
  src/pages/SearchResultPage.tsx
Labels: 🧾 page, 🎁 component, 📍 api, ✨ enhancement

#72 [Feat] 서치바 useOutsideClick 적용 및 기능 개선
  src/App.tsx
  src/components/common/SearchBar.tsx
Labels: 🐞 bug, ✨ enhancement

#74 [Feat] Review Average 컴포넌트 구현
  src/components/review/ReviewAverage.tsx
Labels: 🎁 component, ✨ enhancement

#75 [Feat] 상세페이지
  src/App.tsx
  src/apis/product.ts
  src/assets/icons/arrowRightUp.svg
  src/assets/icons/calendar.svg
  src/assets/icons/location.svg
  src/assets/icons/minus.svg
  src/assets/icons/plus.svg
  src/components/Review.tsx
  src/components/common/CalendarCustom.css
  src/components/common/CalendarCustom.tsx
  src/components/details/DetailsCarousel.tsx
  src/components/details/LocationMap.tsx
  src/components/details/Reservation.tsx
  src/components/details/SalesPeriod.tsx
  src/components/review/ReviewAverage.tsx
  src/constants/types.ts
  src/hooks/useFetchDetails.ts
  src/hooks/useProductReview.ts
  src/pages/ProductDetails.tsx
  src/pages/Reservation.tsx
  src/styles/ProductDetails.css
  src/utils/getDate.ts
Labels: 🧾 page, 🎁 component, 📍 api, ✨ enhancement

#77 [Feat] 리뷰작성 페이지
  src/App.tsx
  src/apis/review.ts
  src/assets/icons/plusUpload.svg
  src/components/ModalExample.tsx
  src/components/common/TextBox.tsx
  src/components/review/ImageUpload.tsx
  src/components/review/ReviewStar.tsx
  src/pages/ReviewRegist.tsx
  src/pages/ReviewRegister.tsx
Labels: 🧾 page, 🐞 bug, 💄 style, ✨ enhancement

#78 [Feat] 상품,옵션 api 리액트 쿼리로 변경 및 사이드바 구현
  src/apis/productAll.ts
  src/assets/icons/defaultImg1.svg
  src/assets/icons/defaultImg2.svg
  src/assets/icons/defaultImg3.svg
  src/assets/icons/defaultImg4.svg
  src/assets/icons/defaultImg5.svg
  src/components/common/headerBar/HeaderBar.tsx
  src/components/common/headerBar/LoginUserHeaderBar.tsx
  src/components/common/headerBar/UnLoginUserHeaderBar.tsx
  src/components/common/layout/Layout.tsx
  src/hooks/reactQuery/product/useProductAll.ts
  src/hooks/reactQuery/product/useProductAllQuery.ts
  src/hooks/useProductAll.ts
  src/hooks/useProductOptionsReviews.ts
  src/hooks/useProductsWithMinPrice.ts
  src/pages/List.tsx
  src/pages/Main.tsx
  src/pages/MyPage.tsx
  src/pages/SearchResultPage.tsx
  src/pages/payments/CheckoutPage.tsx
  src/pages/payments/SuccessPage.tsx
  src/utils/getMinPrice.ts
  src/utils/uniqueProduct.ts
Labels: 🧾 page, 🎁 component, 📍 api, 💄 style, ✨ enhancement

#79 [Feature] checkbutton
  src/pages/productRegist/Category.tsx
  src/pages/productRegist/CheckButton.tsx
  src/pages/productRegist/ProductRegist.tsx
Labels: 🧾 page, 💄 style, ♻️ refactor, ✨ enhancement

#80 [UI] 비밀번호 변경 UI 적용, 사이드바 반응형 적용 및 예약 관리 버튼 구현
  src/assets/icons/arrow-up-right.svg
  src/assets/icons/check-circle.svg
  src/assets/icons/review.svg
  src/assets/icons/square-check.svg
  src/assets/icons/x-square.svg
  src/components/common/InputBox.tsx
  src/components/common/Modal.tsx
  src/components/myPage/ChangePassword.tsx
  src/components/myPage/EditInfo.tsx
  src/components/myPage/MyPageButton.tsx
  src/components/myPage/MyPageSideBar.tsx
  src/components/myPage/MyResevation.tsx
  src/components/myPage/ReservButton.tsx
  src/components/myPage/ReservButtonOutlined.tsx
  src/constants/InputType.ts
  src/mocks/resevationInfo.json
Labels: 💄 style, ♻️ refactor

#81 [Feat] accessToken cookie 저장 및 새로고침 시 지워지는 문제 해결, Button 컴포넌트 type 관련 props 추가
  src/components/common/Button.tsx
  src/pages/auth/login/GoogleRedirect.tsx
  src/pages/auth/login/KakaoRedirect.tsx
  src/pages/auth/login/Login.tsx
  src/pages/auth/login/NaverRedirect.tsx
  src/pages/auth/signup/PartnerSignup.tsx
  src/pages/auth/signup/UserSignup.tsx
  src/utils/cookie.ts
Labels: 🐞 bug, 🎁 component, 📍 api

#82 [Feat] 검색 결과 페이지 구현 완료
  src/components/SearchResultPagination.tsx
  src/components/SearchResultSection.tsx
  src/hooks/useDispalyControl.ts
  src/hooks/useProductsWithMinPrice.ts
  src/pages/Main.tsx
  src/pages/ReviewRegist.tsx
  src/pages/SearchResultPage.tsx
Labels: 🧾 page, 🐞 bug, 🎁 component, 💄 style, ✨ enhancement

#83 [Feature] product Location
  src/assets/icons/check-circle-broken.svg
  src/components/common/map/KakaoMap.tsx
  src/components/common/map/PostCode.tsx
  src/components/details/LocationMap.tsx
  src/pages/productRegist/Category.tsx
  src/pages/productRegist/CheckButton.tsx
  src/pages/productRegist/ImageButton.tsx
  src/pages/productRegist/Location.tsx
Labels: 🧾 page, 🐞 bug, 🎁 component, 💄 style, ✨ enhancement

#85 [Feat] 이미지 업로드 기능 구현
  src/apis/ImageUploadExample.tsx
  src/apis/image.ts
  src/constants/bucket.ts
  src/constants/types.ts
  test.http
Labels: 📍 api, ✨ enhancement

#87 [Feat] 바뀐 데이터 경로 수정 및 필터링 훅, 필터링 버튼 컴포넌트 구현
  src/components/Pay.tsx
  src/components/SearchResultSection.tsx
  src/components/common/FilterButton.tsx
  src/components/common/headerBar/HeaderBar.tsx
  src/components/common/headerBar/LoginUserHeaderBar.tsx
  src/hooks/useFilterByCategory.ts
  src/hooks/useFilterProducts.ts
  src/hooks/usePaymentWidget.ts
  src/hooks/useProductOptionsReviews.ts
  src/hooks/useProductsWithMinPrice.ts
  src/pages/Main.tsx
  src/pages/SearchResultPage.tsx
  src/pages/payments/CheckoutPage.tsx
Labels: 🐞 bug, 🎁 component, ✨ enhancement

#88 [Feat] list page
  src/assets/icons/arrowDown.svg
  src/assets/icons/minusActive.svg
  src/assets/icons/minusInactive.svg
  src/assets/icons/plusActive.svg
  src/assets/icons/plusInactive.svg
  src/assets/icons/search.svg
  src/components/common/CalendarCustom.css
  src/components/common/card/Card.tsx
  src/components/common/card/HotelCard.tsx
  src/components/common/filter/HeadCount.tsx
  src/components/common/filter/PriceRange.tsx
  src/components/common/filter/ProductType.tsx
  src/hooks/reactQuery/product/useProductAll.ts
  src/hooks/useScoreAvg.ts
  src/pages/List.tsx
  src/styles/PriceRange.css
Labels: 🧾 page, 🎁 component, 📍 api, ✨ enhancement

#89 [Feat, Fix] 예약 관리 페이지 변경, ImageButton 컴포넌트 제거 및 Button 컴포넌트 변경 적용
  src/App.tsx
  src/apis/ImageUploadExample.tsx
  src/apis/auth.ts
  src/assets/icons/x-square-red.svg
  src/components/Carousel.tsx
  src/components/MainCard.tsx
  src/components/common/Button.tsx
  src/components/common/SearchBar.tsx
  src/components/common/card/HotelCard.tsx
  src/components/common/headerBar/UnLoginUserHeaderBar.tsx
  src/components/common/map/PostCode.tsx
  src/components/details/Reservation.tsx
  src/components/myPage/ChangePassword.tsx
  src/components/myPage/EditInfo.tsx
  src/components/myPage/MyPageSideBar.tsx
  src/pages/ReservationManagement.tsx
  src/pages/ReviewRegister.tsx
  src/pages/auth/login/Login.tsx
  src/pages/auth/signup/PartnerSignup.tsx
  src/pages/auth/signup/UserSignup.tsx
  src/pages/productRegist/CheckButton.tsx
  src/pages/productRegist/ImageButton.tsx
Labels: 🧾 page, 🎁 component, 💄 style, ♻️ refactor

#90 [Feat & Refactor] 마이페이지 라우트 재설정 및 파트너 메인페이지 구현
  src/App.tsx
  src/components/PartnerMainButton.tsx
  src/components/common/headerBar/LoginUserHeaderBar.tsx
  src/components/myPage/EditInfo.tsx
  src/components/myPage/MyPageButton.tsx
  src/components/myPage/MyPageSideBar.tsx
  src/constants/types.ts
  src/pages/MyPage.tsx
  src/pages/PartnerMain.tsx
  src/utils/jwtDecode.ts
  src/utils/zustand.ts
Labels: 🎁 component, ♻️ refactor

#93 [Feat] 결제 api 연동 성공 및 디자인 구현
  src/apis/payments.ts
  src/apis/product.ts
  src/apis/reservation.ts
  src/apis/timeTable.ts
  src/assets/icons/check-circle-broken-pay.svg
  src/assets/icons/minusPay.svg
  src/assets/icons/plusPay.svg
  src/components/OrderSummary.tsx
  src/hooks/reactQuery/payment/usePaymentPutMutation.ts
  src/hooks/reactQuery/product/useProductionOptionQuery.ts
  src/hooks/reactQuery/reservation/useReservationMutation.ts
  src/hooks/reactQuery/timeTable/useTilmeTabaleOptionQuery.ts
  src/hooks/reactQuery/timeTable/useTimeTableQuery.ts
  src/hooks/usePaymentWidget.ts
  src/hooks/useProductOptionsReviews.ts
  src/hooks/useProductsWithMinPrice.ts
  src/hooks/useSearchData.ts
  src/pages/SearchResultPage.tsx
  src/pages/payments/CheckoutPage.tsx
  src/pages/payments/SuccessPage.tsx
Labels: 🧾 page, 🐞 bug, 🎁 component, 📍 api, 💄 style

#92 [Feat] NumberInput 컴포넌트 구현, description페이지와 Option페이지 기초구현
  src/assets/icons/search-pr.svg
  src/components/common/InputBox.tsx
  src/components/common/NumberInputBox.tsx
  src/components/common/map/PostCode.tsx
  src/pages/productRegist/Category.tsx
  src/pages/productRegist/Description.tsx
  src/pages/productRegist/Option.tsx
Labels: 🧾 page, 🎁 component, 💄 style

#94 [Feat] 상품상세, 리스트, 리뷰작성페이지 개선 및 기능 추가
  src/App.tsx
  src/components/common/card/Card.tsx
  src/components/common/filter/ProductType.tsx
  src/components/details/LocationMap.tsx
  src/components/details/Reservation.tsx
  src/components/details/SalesPeriod.tsx
  src/components/review/ImageUpload.tsx
  src/constants/month.ts
  src/hooks/reactQuery/product/useProductAll.ts
  src/hooks/useSearchData.ts
  src/hooks/useTimeTable.ts
  src/pages/List.tsx
  src/pages/ProductDetails.tsx
  src/pages/ReviewRegister.tsx
  src/styles/PriceRange.css
  src/utils/getDate.ts
  src/utils/getMinPrice.ts
  src/utils/zustand.ts
Labels: 🧾 page, 🎁 component, 📍 api, ✨ enhancement

#95 [Feat] 예약 관리 페이지 reservation API 연결, reservationStatus 변경 동작 구현, 경로 변경, 반응형 동작 구현
  src/App.tsx
  src/components/ReservedManageCard.tsx
  src/components/common/layout/layoutSample.tsx
  src/components/common/reservPagination/ResevationCard.tsx
  src/components/myPage/MyPageSideBar.tsx
  src/constants/constantSample.ts
  src/constants/reserveType.ts
  src/pages/MyPage.tsx
  src/pages/ReservationManagement.tsx
Labels: 🧾 page, 🎁 component, 📍 api, ♻️ refactor, ✨ enhancement

#96 [Fix] Card내 날짜 출력 방식 변경을 위한 함수 정의 및 적용(0000.00.00), ReservChips 반환 형식 변경
  src/assets/icons/status-approved.svg
  src/assets/icons/status-chip-approved.svg
  src/assets/icons/status-chip-pending.svg
  src/assets/icons/status-chip-rejected.svg
  src/assets/icons/status-pending.svg
  src/assets/icons/status-rejected.svg
  src/components/ReservedManageCard.tsx
  src/components/myPage/ReservChips.tsx
  src/constants/reserveType.ts
  src/pages/ReservationManagement.tsx
  src/utils/changeDateForm.ts
Labels: 🎁 component, 💄 style, ♻️ refactor

#97 [Refactor] 수정된 api에 맞게 메인, 검색결과, 결제페이지 코드 수정
  src/components/SearchResultSection.tsx
  src/components/common/SearchBar.tsx
  src/components/common/headerBar/LoginUserHeaderBar.tsx
  src/hooks/reactQuery/reservation/useReservationMutation.ts
  src/hooks/useFilterByCategory.ts
  src/hooks/useFilterProducts.ts
  src/hooks/useProductsWithMinPrice.ts
  src/pages/Main.tsx
  src/pages/SearchResultPage.tsx
  src/pages/payments/CheckoutPage.tsx
  src/pages/payments/SuccessPage.tsx
Labels: 🐞 bug, 📍 api

#98 [Refactor] 예약 현황, 예약 내역 분리 및 경로 분리
  package-lock.json
  package.json
  src/apis/myReservation.ts
  src/assets/icons/x-square.svg
  src/components/ReservedManageCard.tsx
  src/components/common/reservPagination/ResevationCard.tsx
  src/components/myPage/CancelMessage.tsx
  src/components/myPage/EditInfo.tsx
  src/components/myPage/MyPageSideBar.tsx
  src/components/myPage/MyResevation.tsx
  src/components/myPage/ReservButton.tsx
  src/components/myPage/ReservButtonOutlined.tsx
  src/components/myPage/ReservChips.tsx
  src/components/myPage/ReservChipsExpired.tsx
  src/constants/types.ts
  src/index.js
  src/pages/MyPage.tsx
  src/pages/ReservationManagement.tsx
Labels: 🎁 component, ✨ enhancement, ⚙️ setting

#99 [Refactor] 일반 유저 로그인, 파트너 로그인 시 다른 화면 렌더링
  src/components/common/headerBar/LoginUserHeaderBar.tsx
  src/components/common/headerBar/UnLoginUserHeaderBar.tsx
  src/pages/Main.tsx
Labels: 🐞 bug, ♻️ refactor

#100 [Feat] 달력 컴포넌트 수정, api 정리, 필터링 정보 받아오기
  package-lock.json
  package.json
  src/apis/product.ts
  src/apis/productAll.ts
  src/apis/productOption.ts
  src/apis/review.ts
  src/components/common/filter/CategoryTypes.ts
  src/components/common/filter/HeadCount.tsx
  src/components/common/filter/PriceRange.tsx
  src/components/common/filter/ProductType.tsx
  src/components/details/DatePickerCustom.css
  src/components/details/DatePickerCustom.tsx
  src/components/details/DetailInfo.tsx
  src/constants/types.ts
  src/hooks/reactQuery/product/useProductAll.ts
  src/hooks/reactQuery/product/useProductionOptionQuery.ts
  src/hooks/useDatePicker.ts
  src/hooks/useFetchDetails.ts
  src/hooks/useTypeCheckbox.ts
  src/pages/List.tsx
  src/pages/ProductDetails.tsx
  src/utils/uniqueProduct.ts
Labels: 🧾 page, 🎁 component, 📍 api, ♻️ refactor, ✨ enhancement

#101 [Api] product 테이블 리액트 쿼리 훅 모두 작성 및 적용
  src/components/common/headerBar/HeaderBar.tsx
  src/hooks/reactQuery/product/useProductAll.ts
  src/hooks/reactQuery/product/useProductAllQuery.ts
  src/hooks/reactQuery/product/useProductByIdQuery.ts
  src/hooks/reactQuery/product/useProductDeleteMutation.ts
  src/hooks/reactQuery/product/useProductPostMutation.ts
  src/hooks/reactQuery/product/useProductPutMutation.ts
  src/hooks/reactQuery/productOption/useProductOptionAllQuery.ts
  src/hooks/reactQuery/productOption/useProductOptionQuery.ts
  src/hooks/reactQuery/review/useReviewAllQuery.ts
  src/hooks/useFetchDetails.ts
  src/hooks/useFetchReview.ts
  src/hooks/useProductReview.ts
  src/hooks/useScoreAvg.ts
  src/pages/List.tsx
  src/pages/Main.tsx
  src/pages/ReviewRegister.tsx
  src/pages/SearchResultPage.tsx
  src/pages/payments/CheckoutPage.tsx
Labels: 🐞 bug, 📍 api

#102 [API] Auth(로그인, 회원가입) React Query 적용 완료, 기타 버그 수정
  src/apis/auth.ts
  src/components/common/reservPagination/ResevationCard.tsx
  src/hooks/reactQuery/auth/useLoginMutation.ts
  src/hooks/reactQuery/auth/useSignupMutation.ts
  src/hooks/reactQuery/auth/useSocialLoginMutation.ts
  src/hooks/reactQuery/auth/useVerifyEmail.ts
  src/hooks/useOAuthLogin.ts
  src/pages/ReservationManagement.tsx
  src/pages/auth/login/GoogleRedirect.tsx
  src/pages/auth/login/KakaoRedirect.tsx
  src/pages/auth/login/Login.tsx
  src/pages/auth/login/NaverRedirect.tsx
  src/pages/auth/signup/PartnerSignup.tsx
  src/pages/auth/signup/UserSignup.tsx
Labels: 🐞 bug, 📍 api, ✨ enhancement

#103 [Style] 404페이지, 서비스 준비중 페이지, 로딩 스피너 구현
  src/App.tsx
  src/assets/icons/ing.svg
  src/assets/icons/no-page.svg
  src/components/common/Loading.tsx
  src/components/common/headerBar/HeaderBar.tsx
  src/pages/Main.tsx
  src/pages/NoPage.tsx
  src/pages/PreparingPage.tsx
  src/pages/SearchResultPage.tsx
  src/pages/payments/CheckoutPage.tsx
  src/pages/payments/SuccessPage.tsx
Labels: 🧾 page, 🎁 component, 💄 style

#104 [UI] 장바구니 페이지 UI 구현
  src/App.tsx
  src/components/CartList.tsx
  src/pages/Cart.tsx
Labels: 🧾 page, 🎁 component, 💄 style

#105 [Feature] picture
  src/assets/icons/trash-red.svg
  src/components/common/Button.tsx
  src/components/common/map/PostCode.tsx
  src/pages/productRegist/Category.tsx
  src/pages/productRegist/CheckButton.tsx
  src/pages/productRegist/Date.tsx
  src/pages/productRegist/Description.tsx
  src/pages/productRegist/ImgModal.tsx
  src/pages/productRegist/Location.tsx
  src/pages/productRegist/ProductRegist.tsx
  src/pages/productRegist/productPage.d.ts
Labels: 🧾 page, 🐞 bug, 💄 style, ✨ enhancement

#106 [Feat] react-query 적용, 캘린더 수정
  src/App.tsx
  src/apis/product.ts
  src/apis/productOption.ts
  src/components/Review.tsx
  src/components/common/card/HotelCard.tsx
  src/components/details/DatePickerCustom.css
  src/components/details/DatePickerCustom.tsx
  src/components/details/Reservation.tsx
  src/constants/types.ts
  src/hooks/reactQuery/product/useProductByIdQuery.ts
  src/hooks/reactQuery/productOption/useProductOptionByProductIdQuery.ts
  src/hooks/reactQuery/productOption/useProductOptionDeleteMutation.ts
  src/hooks/reactQuery/productOption/useProductOptionPostMutation.ts
  src/hooks/reactQuery/productOption/useProductOptionPutMutation.ts
  src/hooks/reactQuery/productOption/useProductOptionQuery.ts
  src/hooks/reactQuery/review/useReviewAllQuery.ts
  src/hooks/reactQuery/review/useReviewByProductIdQuery.ts
  src/hooks/reactQuery/review/useReviewByReviewIdQuery.ts
  src/hooks/reactQuery/review/useReviewDeleteMutation.ts
  src/hooks/reactQuery/review/useReviewPostMutation.ts
  src/hooks/reactQuery/review/useReviewPutMutation.ts
  src/hooks/useDatePicker.ts
  src/hooks/useFetchDetails.ts
  src/hooks/useFetchReview.ts
  src/hooks/useProductReview.ts
  src/hooks/useTimeTable.ts
  src/pages/List.tsx
  src/pages/ProductDetails.tsx
  src/pages/payments/CheckoutPage.tsx
  src/utils/getDate.ts
  src/utils/getMinPrice.ts
Labels: 🧾 page, 🎁 component, 📍 api, ♻️ refactor, ✨ enhancement

#107 [Refactor] 프로필 이미지 업로드 및 예약 버튼 로직 개선
  src/App.tsx
  src/apis/image.ts
  src/assets/icons/x-circle-custom.svg
  src/components/MainCard.tsx
  src/components/ReservedManageCard.tsx
  src/components/SearchResultSection.tsx
  src/components/common/card/CardSample.tsx
  src/components/common/card/HotelCard.tsx
  src/components/common/filter/ProductType.tsx
  src/components/common/headerBar/HeaderBar.tsx
  src/components/common/headerBar/LoginUserHeaderBar.tsx
  src/components/common/layout/Layout.tsx
  src/components/common/reservPagination/ResevationCard.tsx
  src/components/details/Reservation.tsx
  src/components/myPage/EditInfo.tsx
  src/components/myPage/MyResevation.tsx
  src/components/myPage/ReservButton.tsx
  src/pages/Main.tsx
  src/pages/MyPage.tsx
  src/pages/ReviewRegist.tsx
  src/pages/productRegist/ProductRegist.tsx
  src/utils/axios.ts
Labels: ♻️ refactor

#109 [Feat] 리뷰작성페이지 완성! 상세페이지 리뷰tab 개선
  src/App.tsx
  src/apis/image.ts
  src/apis/product.ts
  src/apis/productOption.ts
  src/apis/review.ts
  src/components/Review.tsx
  src/components/common/card/HotelCard.tsx
  src/components/common/headerBar/HeaderBar.tsx
  src/components/review/ReviewAverage.tsx
  src/constants/types.ts
  src/hooks/reactQuery/product/useProductByIdQuery.ts
  src/hooks/reactQuery/productOption/useProductOptionByProductIdQuery.ts
  src/hooks/reactQuery/review/useReviewByProductIdQuery.ts
  src/hooks/useFetchDetails.ts
  src/hooks/useProductReview.ts
  src/hooks/useReviewDefaults.ts
  src/pages/ProductDetails.tsx
  src/pages/ReviewRegist.tsx
  src/pages/ReviewRegister.tsx
  src/pages/payments/CheckoutPage.tsx
  src/utils/uniqueProduct.ts
Labels: 🧾 page, 🎁 component, 📍 api, ✨ enhancement

#112 [Feat, API] 파트너 게시물 관리 페이지 링크 연결, 구현 및 관련 API, hook 추가, 파트너 메인 페이지 내 버튼 클릭 시 링크 이동 추가
  src/apis/product.ts
  src/components/ReservedManageCard.tsx
  src/components/myPage/MyPageSideBar.tsx
  src/hooks/reactQuery/product/useProductByPartnerQuery.ts
  src/pages/MyPage.tsx
  src/pages/PartnerMain.tsx
  src/pages/PostingManagement.tsx
  src/pages/ReservationManagement.tsx
Labels: 🧾 page, 🐞 bug, 🎁 component, 📍 api, ✨ enhancement

#113 [Fix, Feat] reservationState Type 변경, 게시물 관리 디자인 요소 추가(switch, card)
  src/components/ManageSearchBar.tsx
  src/components/PostingCard.tsx
  src/components/ReservedManageCard.tsx
  src/components/common/Switch.tsx
  src/components/myPage/MyResevation.tsx
  src/components/myPage/ReservButton.tsx
  src/components/myPage/ReservButtonOutlined.tsx
  src/components/myPage/ReservChips.tsx
  src/components/myPage/ReservChipsExpired.tsx
  src/constants/reserveType.ts
  src/constants/types.ts
  src/mocks/resevationInfo.json
  src/pages/PostingManagement.tsx
  src/pages/ReservationManagement.tsx
  src/styles/global.css
  src/styles/switch.css
Labels: 🖼️ layout, 🐞 bug, 🎁 component, 💄 style

#114 [Feature] Option페이지 구현, imageModal 수정
  src/App.tsx
  src/assets/icons/plus-blue.svg
  src/assets/icons/plus-white.svg
  src/assets/icons/uploadBox.svg
  src/components/common/Modal.tsx
  src/components/common/NumberInputBox.tsx
  src/components/common/map/PostCode.tsx
  src/pages/productRegist/Category.tsx
  src/pages/productRegist/ImgModal.tsx
  src/pages/productRegist/Option.tsx
  src/pages/productRegister/Category.tsx
  src/pages/productRegister/CheckButton.tsx
  src/pages/productRegister/Date.tsx
  src/pages/productRegister/Description.tsx
  src/pages/productRegister/ImgModal.tsx
  src/pages/productRegister/Location.tsx
  src/pages/productRegister/Option.tsx
  src/pages/productRegister/OptionModal.tsx
  src/pages/productRegister/ProductRegister.tsx
  src/pages/productRegister/productPage.d.ts
  src/utils/zustand.ts
Labels: 🧾 page, 💄 style, ✨ enhancement

#115 [Feature] 기본 모달, 토스트 기능 추가
  package-lock.json
  package.json
  src/components/common/Button.tsx
  src/components/common/DefaultModal.tsx
  src/components/myPage/CancelMessage.tsx
  src/components/myPage/EditInfo.tsx
  src/components/myPage/Modal/CancelReserv.tsx
  src/components/myPage/Modal/CheckCancelMsg.tsx
  src/components/myPage/MyResevation.tsx
  src/example/DefaultModalExample.tsx
  src/example/ImageUploadExample.tsx
  src/example/ModalExample.tsx
  src/example/ReservationPaginationExample.tsx
  src/example/ToastExample.tsx
  src/index.js
Labels: 🎁 component, 💄 style, ✨ enhancement

#116 [Feat] 장바구니 담기 및 결제 페이지, 결제 실패 페이지 구현 완료
  src/App.tsx
  src/apis/cart.ts
  src/assets/icons/noPay.svg
  src/components/CartList.tsx
  src/components/CartPay.tsx
  src/components/Pay.tsx
  src/components/common/headerBar/LoginUserHeaderBar.tsx
  src/hooks/reactQuery/cart/useCartByUserIdQuery.ts
  src/hooks/reactQuery/cart/useCartDeleteByCartIdMutation.ts
  src/hooks/reactQuery/cart/useCartPostMutation.ts
  src/hooks/reactQuery/cart/useCartReservationByUserIdMutation.ts
  src/hooks/reactQuery/payment/usePaymentPutMutation.ts
  src/pages/Cart.tsx
  src/pages/payments/CheckoutCartPage.tsx
  src/pages/payments/FailPage.tsx
  src/pages/payments/SuccessPage.tsx
  src/utils/zustand.ts
Labels: 🧾 page, 🐞 bug, 🎁 component, 📍 api, 💄 style, ✨ enhancement

#117 [Feat] Date기능
  src/components/myPage/MyResevation.tsx
  src/pages/productRegister/Date.tsx
Labels: 🧾 page, 💄 style, ✨ enhancement

#118 [Refactor] 디테일 페이지 경로 수정 및 로그인 안된 유저 페이지 겁근 막는 컴포넌트 추가
  src/App.tsx
  src/components/ProtectedRoute.tsx
  src/components/SearchResultSection.tsx
  src/pages/Main.tsx
Labels: 🎁 component, ♻️ refactor

#120 [Fix, 배포] 배포 관련 추가 설정, Switch 관련 설정 추가
  netlify.toml
  package.json
  public/_redirects
  src/apis/image.ts
  src/apis/payments.ts
  src/apis/timeTable.ts
  src/components/Review.tsx
  src/components/common/Switch.tsx
  src/components/details/Reservation.tsx
  src/components/myPage/ChangePassword.tsx
  src/components/myPage/EditInfo.tsx
  src/hooks/useDatePicker.ts
  src/hooks/usePaymentWidget.ts
  src/pages/List.tsx
  src/pages/PostingManagement.tsx
  src/pages/ReviewRegister.tsx
  src/pages/auth/signup/PartnerSignup.tsx
  src/pages/auth/signup/UserSignup.tsx
  src/pages/productRegister/Description.tsx
  src/pages/productRegister/ImgModal.tsx
  src/pages/productRegister/Option.tsx
  src/pages/productRegister/OptionModal.tsx
  src/pages/productRegister/ProductRegister.tsx
  src/utils/zustand.ts
Labels: 🐞 bug, ⚙️ setting

#121 [Feat] 게시물 관리 구현, 사이트 title 설정, https 생성 태그 생성, 게시물 삭제 및 거절 사유 작성 버튼 클릭 시 modal 기능 구현(초기)
  public/index.html
  src/apis/product.ts
  src/apis/reservation.ts
  src/assets/icons/arrow-up-right-blue.svg
  src/components/ReservedManageCard.tsx
  src/components/common/Switch.tsx
  src/components/myPage/Modal/DeletePosting.tsx
  src/components/myPage/Modal/RejectReservation.tsx
  src/components/myPage/PostingSwitch.tsx
  src/components/myPage/ReservButtonOutlined.tsx
  src/hooks/reactQuery/auth/useLoginMutation.ts
  src/hooks/reactQuery/auth/useVerifyEmail.ts
  src/hooks/reactQuery/product/usePostingStateMutation.ts
  src/pages/PostingManagement.tsx
Labels: 🧾 page, 🐞 bug, 🎁 component, 📍 api, ⚙️ setting

#123 [Feat] 리스트페이지 필터링 구현 및 상품페이지 마무리
  src/App.tsx
  src/apis/product.ts
  src/components/Review.tsx
  src/components/common/NoData.tsx
  src/components/common/card/Card.tsx
  src/components/common/filter/ProductType.tsx
  src/components/details/DatePickerCustom.tsx
  src/components/details/DetailInfo.tsx
  src/components/details/Reservation.tsx
  src/constants/CategoryTypes.ts
  src/constants/types.ts
  src/hooks/useDatePicker.ts
  src/hooks/useFetchByCategory.ts
  src/hooks/useFetchDetails.ts
  src/hooks/useFetchOptionByOptionId.ts
  src/pages/List.tsx
  src/pages/ProductDetails.tsx
  src/pages/ReviewRegister.tsx
  src/pages/productRegister/Date.tsx
Labels: 🧾 page, 🐞 bug, 🎁 component, ♻️ refactor, ✨ enhancement

#124 [Refactor] 헤더바 반응형 완료
  src/components/CartList.tsx
  src/components/MainCategoryButton.tsx
  src/components/common/headerBar/HeaderBar.tsx
  src/components/details/Reservation.tsx
  src/hooks/reactQuery/cart/useCartReservationByUserIdMutation.ts
  src/hooks/reactQuery/reservation/useReservationMutation.ts
  src/pages/payments/CheckoutPage.tsx
  src/pages/payments/SuccessPage.tsx
  src/utils/zustand.ts
Labels: 🐞 bug, 📍 api, 💄 style, ♻️ refactor

#126 [Feat, Design] 예약 거절 메세지 작성 modal 및 파트너 게시물 작성 modal 구현, 예약 관리 button 디자인 수정
  src/apis/reservation.ts
  src/components/ReservedManageCard.tsx
  src/components/myPage/Modal/RejectReservation.tsx
  src/components/myPage/ReservButtonOutlined.tsx
  src/pages/PostingManagement.tsx
Labels: 🐞 bug, 🎁 component, 💄 style, ✨ enhancement

#125 [Refactor] 마이페이지 api 및 스타일 재조정
  src/apis/myReservation.ts
  src/apis/reservation.ts
  src/components/ReservedManageCard.tsx
  src/components/common/Footer.tsx
  src/components/common/filter/PriceRange.tsx
  src/components/common/headerBar/HeaderBar.tsx
  src/components/common/headerBar/LoginUserHeaderBar.tsx
  src/components/common/layout/Layout.tsx
  src/components/details/Reservation.tsx
  src/components/myPage/ChangePassword.tsx
  src/components/myPage/EditInfo.tsx
  src/components/myPage/Modal/CancelReserv.tsx
  src/components/myPage/MyPageSideBar.tsx
  src/components/myPage/MyResevation.tsx
  src/components/myPage/ReservButton.tsx
  src/components/myPage/ReservButtonOutlined.tsx
  src/components/myPage/ReservChips.tsx
  src/components/myPage/ReservChipsExpired.tsx
  src/constants/reserv.ts
  src/example/DefaultModalExample.tsx
  src/example/ImageUploadExample.tsx
  src/example/ModalExample.tsx
  src/example/ReservationPaginationExample.tsx
  src/example/ToastExample.tsx
  src/hooks/reactQuery/reservation/useReservationMutation.ts
  src/mocks/resevationInfo.json
  src/pages/PartnerMain.tsx
  src/utils/zustand.ts
Labels: 🎁 component, 📍 api, 💄 style, ♻️ refactor

#128 [Refactor] 결제 버그 문제 해결 및 결제 페이지 옶션, 시간 알맞게 변경
  src/components/OrderSummary.tsx
  src/components/SearchResultSection.tsx
  src/pages/SearchResultPage.tsx
  src/pages/payments/CheckoutPage.tsx
  src/pages/payments/SuccessPage.tsx
Labels: 🐞 bug, 📍 api, ♻️ refactor

#127 [Feat] Post기능
  public/index.html
  src/apis/product.ts
  src/hooks/reactQuery/product/useProductPostMutation.ts
  src/hooks/reactQuery/product/useProductPutMutation.ts
  src/pages/productRegister/Category.tsx
  src/pages/productRegister/Date.tsx
  src/pages/productRegister/Description.tsx
  src/pages/productRegister/Option.tsx
  src/pages/productRegister/ProductRegister.tsx
  src/utils/zustand.ts
Labels: 🧾 page, 🐞 bug, 📍 api

#131 [fix] 결제 count 버그 해결
  src/pages/payments/CheckoutPage.tsx
Labels: 🐞 bug

#133 [Refactor] 인원수 필터링 직접 입력 안되는 버그 해결
  src/components/common/filter/PriceRange.tsx
  src/components/review/ReviewStar.tsx
Labels: 🐞 bug, 🎁 component, 💄 style, ✨ enhancement

#135 [Style] 메인 페이지 캐러셀 디자인 구현 완료
  src/assets/icons/carouselarrow.svg
  src/assets/icons/carouselarrow2.svg
  src/assets/images/carousel.jpg
  src/assets/images/carousel2.jpg
  src/assets/images/carousel3.jpg
  src/components/Carousel.tsx
  src/components/MainCard.tsx
  src/components/common/card/Card.tsx
  src/pages/Main.tsx
  src/pages/payments/SuccessPage.tsx
  tailwind.config.js
Labels: 💄 style

#134 [Fix] 비로그인 상태에서 결제 / 장바구니 클릭 시 로그인페이지로 이동
  public/index.html
  src/components/common/CalendarCustom.tsx
  src/components/details/DatePickerCustom.tsx
  src/components/details/Reservation.tsx
  src/constants/types.ts
Labels: 🐞 bug

#137 [Feat] post 기능 완성
  src/apis/product.ts
  src/hooks/reactQuery/product/useProductPostMutation.ts
  src/hooks/reactQuery/product/useProductPutMutation.ts
  src/pages/productRegister/Option.tsx
  src/utils/zustand.ts
Labels: 🐞 bug, 📍 api

#138 [Fix] 결제 페이지 reservation api 두번 요청되는 이슈 해결
  src/components/common/headerBar/LoginUserHeaderBar.tsx
  src/pages/payments/SuccessPage.tsx
Labels: 🐞 bug, ♻️ refactor

#139 [Fix] 이메일 중복 확인 없이 회원가입 되던 문제 및 회원가입 시 Error 동작 수정, Toast 내부 text 크기 및 font 굵기 수정
  src/hooks/reactQuery/auth/useSignupMutation.ts
  src/index.js
  src/pages/auth/signup/PartnerSignup.tsx
  src/pages/auth/signup/UserSignup.tsx
  src/pages/payments/SuccessPage.tsx
Labels: 🐞 bug, 💄 style

#140 [Feat] 리뷰작성페이지 수정하기 기능 구현
  src/App.tsx
  src/apis/review.ts
  src/components/review/ImageUpload.tsx
  src/components/review/ReviewStar.tsx
  src/constants/types.ts
  src/hooks/reactQuery/review/useReviewByReviewIdQuery.ts
  src/hooks/useFetchReview.ts
  src/hooks/useGetUserIdByReviewId.ts
  src/hooks/useProductReview.ts
  src/hooks/useReviewDefaults.ts
  src/pages/ReviewRegist.tsx
  src/pages/ReviewRegister.tsx
Labels: 🧾 page, 📍 api, ✨ enhancement

#141 [fix] destroy에러 해결
  src/hooks/useDatePicker.ts
Labels: 🐞 bug, ♻️ refactor

#143 [Fix] switch on/off, 삭제하기 동작 후 내용이 바로 반영되도록 수정, 예약 관리-예약 거절 시 '취소하기' 버튼 삭제 외
  src/components/PostingCard.tsx
  src/components/ReservedManageCard.tsx
  src/components/myPage/Modal/DeletePosting.tsx
  src/hooks/reactQuery/product/usePostingStateMutation.ts
  src/hooks/reactQuery/product/useProductDeleteMutation.ts
  src/pages/PostingManagement.tsx
Labels: 🐞 bug, 🎁 component

#144 [Fix] 마이페이지 이슈 수정
  src/App.tsx
  src/components/myPage/ChangePassword.tsx
  src/components/myPage/EditInfo.tsx
  src/components/myPage/MyPageSideBar.tsx
  src/constants/InputType.ts
Labels: 💄 style, ♻️ refactor

#147 [Refactor] 예약 시 가격, 숙박용 카드
  src/components/common/card/HotelCard.tsx
  src/components/details/Reservation.tsx
  src/components/review/ImageUpload.tsx
  src/pages/ProductDetails.tsx
  src/pages/ReviewRegister.tsx
Labels: 🐞 bug, ♻️ refactor

#148 [Fix, Design] 게시물 관리, 예약 관리 반응형 동작 추가, 소셜 로그인 디자인 수정, 회원가입 닉네임 오류 수정
  public/index.html
  src/assets/icons/travelPortLogo-login.svg
  src/components/PostingCard.tsx
  src/pages/PostingManagement.tsx
  src/pages/ReservationManagement.tsx
  src/pages/auth/login/Login.tsx
  src/pages/auth/signup/PartnerSignup.tsx
  src/pages/auth/signup/UserSignup.tsx
Labels: 🐞 bug, 🎁 component, 💄 style

#150 [Style] 메인페이지 로딩 스피너 대신 스켈레톤으로 구현
  src/assets/icons/headerSearchButton.svg
  src/assets/icons/smallCart.svg
  src/components/Carousel.tsx
  src/components/MainCard.tsx
  src/components/MainCategoryButton.tsx
  src/components/common/Footer.tsx
  src/components/common/Skeleton.tsx
  src/components/common/headerBar/LoginUserHeaderBar.tsx
  src/pages/Main.tsx
Labels: 🎁 component, 💄 style

#152 [Fix] 결제페이지, 장바구니 null 뜨는 에러 해결
  src/components/CartList.tsx
  src/hooks/reactQuery/productOption/useProductOptionQuery.ts
  src/hooks/reactQuery/timeTable/useTimeTableQuery.ts
  src/pages/Cart.tsx
  src/pages/payments/CheckoutPage.tsx
Labels: 🐞 bug

#151 [refactor] 다양한 에러 해결
  src/components/details/DatePickerCustom.tsx
  src/components/details/DetailInfo.tsx
  src/components/details/Reservation.tsx
  src/pages/List.tsx
  src/pages/ProductDetails.tsx
Labels: ♻️ refactor

#153 [Fix] 마이페이지 이슈 해결 및 api 수정
  src/App.tsx
  src/apis/image.ts
  src/components/PostingCard.tsx
  src/components/ProtectedRoute.tsx
  src/components/ReservedManageCard.tsx
  src/components/common/layout/Layout.tsx
  src/components/myPage/EditInfo.tsx
  src/components/myPage/Modal/CancelReserv.tsx
  src/components/myPage/MyReservation.tsx
  src/components/myPage/ReservChips.tsx
  src/constants/reserv.ts
  src/constants/types.ts
  src/pages/Cart.tsx
  src/pages/List.tsx
  src/pages/Main.tsx
  src/pages/MyPage.tsx
  src/pages/PartnerMain.tsx
  src/pages/ProductDetails.tsx
  src/pages/ReviewRegist.tsx
  src/pages/SearchResultPage.tsx
  src/pages/payments/CheckoutCartPage.tsx
  src/pages/payments/CheckoutPage.tsx
  src/utils/axios.ts
Labels: 🧾 page, 🐞 bug, 📍 api

#155 [Feat] sidebar 기능 구현, disabled처리, 메인로고
  src/components/common/map/PostCode.tsx
  src/pages/auth/login/Login.tsx
  src/pages/auth/signup/PartnerSignup.tsx
  src/pages/auth/signup/UserSignup.tsx
  src/pages/productRegister/Category.tsx
  src/pages/productRegister/CheckButton.tsx
  src/pages/productRegister/Description.tsx
  src/pages/productRegister/Location.tsx
  src/pages/productRegister/Option.tsx
  src/pages/productRegister/OptionModal.tsx
  src/pages/productRegister/ProductRegister.tsx
  src/pages/productRegister/productPage.d.ts
Labels: 🐞 bug, 📍 api, 💄 style

#154 [Feat, Fix] Favicon 설정,
  public/favicon.ico
  public/favicon_dark.ico
  public/index.html
  src/components/PostingCard.tsx
  src/components/common/reservPagination/ReservationCard.tsx
  src/pages/PostingManagement.tsx
  src/pages/ReservationManagement.tsx
Labels: 🧾 page, 🎁 component, 💄 style

#156 [Refactor] 일정에 따른 마감 처리 구현
  src/components/details/Reservation.tsx
Labels: 🐞 bug, ✨ enhancement

#157 [Style] 디자인 바뀐 헤더 1차 변경
  src/assets/icons/pcLogo.svg
  src/components/Carousel.tsx
  src/components/MainCategoryButton.tsx
  src/components/common/headerBar/HeaderBar.tsx
Labels: 💄 style

#159 [Docs & Fix] README.md 작성 및
  README.md
  public/img/TravelPort_userflow.png
  src/apis/reservation.ts
  src/hooks/reactQuery/reservation/useReservationManageQuery.ts
  src/pages/partner/ReservationManagement.tsx
  test.http
Labels: 📍 api, 📄 docs

#160 [Style] 디자인 바뀐 메인페이지 수정 완료
  src/assets/icons/plusArrowButton.svg
  src/assets/images/carousel.jpg
  src/assets/images/carousel1.jpg
  src/assets/images/carousel2.jpg
  src/assets/images/carousel3.jpg
  src/components/common/layout/Layout.tsx
  src/components/common/layout/headerBar/HeaderBar.tsx
  src/components/main/Carousel.tsx
  src/components/main/MainCard.tsx
  src/components/main/MainCategoryButton.tsx
  src/pages/user/Main.tsx
  tailwind.config.js
Labels: 💄 style

#161 [Fix] searchbar border 수정
  .eslintrc.json
  src/styles/global.css
Labels: 💄 style, ⚙️ setting

#163 [Fix] productRegister 오류 수정
  src/pages/partner/productRegister/DateCheck.tsx
  src/pages/partner/productRegister/Description.tsx
  src/pages/partner/productRegister/Option.tsx
  src/pages/partner/productRegister/OptionModal.tsx
Labels: 🐞 bug, 💄 style, ♻️ refactor

#162 [Fix] 결제 페이지 몇박인지 작성
  src/components/common/layout/headerBar/HeaderBar.tsx
  src/pages/user/cart/Cart.tsx
  src/pages/user/payments/CheckoutCartPage.tsx
  src/pages/user/payments/CheckoutPage.tsx
  src/pages/user/payments/SuccessPage.tsx
  src/utils/Zustand.ts
Labels: 🐞 bug

#164 [Fix] 불필요한 eslint 삭제 및 마이페이지 헤더 이슈 해결
  src/App.tsx
  src/apis/productOption.ts
  src/apis/review.ts
  src/components/common/SearchBar.tsx
  src/components/details/Reservation.tsx
  src/components/main/Carousel.tsx
  src/components/myPage/EditInfo.tsx
  src/components/reservation/ManageSearchBar.tsx
  src/components/review/ImageUpload.tsx
  src/components/review/ReviewStar.tsx
  src/hooks/functionHooks/useSearchData.ts
  src/hooks/products/useFilterProducts.ts
  src/hooks/products/useProductsWithMinPrice.ts
  src/pages/MyPage.tsx
  src/pages/user/List.tsx
  src/pages/user/Main.tsx
  src/pages/user/ProductDetails.tsx
  src/pages/user/cart/Cart.tsx
  src/pages/user/review/ReviewRegister.tsx
  src/utils/Cookie.ts
Labels: 🖼️ layout, 📄 docs

#165 [Style] 장바구니에 1박 text 고정
  src/components/cart/CartList.tsx
  src/pages/user/cart/Cart.tsx
  src/pages/user/payments/CheckoutPage.tsx
Labels: 💄 style

#166 [Fix] min, timetable, 이미지, 전체 주석처리
  src/components/common/card/Card.tsx
  src/components/common/map/KakaoMap.tsx
  src/pages/partner/productRegister/ImgModal.tsx
  src/pages/partner/productRegister/Location.tsx
  src/pages/partner/productRegister/Option.tsx
  src/pages/partner/productRegister/productPage.d.ts
Labels: 🐞 bug, ♻️ refactor

#167 [Fix] 다양한 에러 해결
  public/index.html
  src/App.tsx
  src/components/details/Reservation.tsx
  src/components/list/filter/PriceRange.tsx
Labels: 🐞 bug

#168 [Docs] Update README.md
  README.md
Labels: 📄 docs

#169 [Refactor] 코드 refactoring 및 비밀번호 확인(eye 버튼) 추가
  netlify.toml
  public/_redirects
  src/apis/auth.ts
  src/assets/icons/eyeoff.svg
  src/assets/icons/eyeon.svg
  src/components/common/input/InputBox.tsx
  src/components/details/Reservation.tsx
  src/components/myPage/PostingSwitch.tsx
  src/hooks/auth/useOAuthLogin.ts
  src/pages/partner/ReservationManagement.tsx
Labels: 🎁 component, 💄 style, ✨ enhancement

#171 [Fix] 장바구니 결제 이슈 해결
  src/pages/user/payments/SuccessPage.tsx
  src/utils/Zustand.ts
Labels: 🐞 bug

#173 [Fix] 도메인 설정에 따른 redirect 링크 재설정
  src/hooks/auth/useOAuthLogin.ts
Labels: 📍 api

#172 [Fix] 예약 취소 안되던 버그 수정
  src/apis/myReservation.ts
  src/components/myPage/MyReservation.tsx
  src/constants/Reserv.ts
  src/constants/Types.ts
Labels: 🐞 bug

#174 [Fix] 리뷰 프로필 이미지 반영
  src/components/review/Review.tsx
Labels: 🐞 bug

#175 [Fix] 리뷰 프로필 이미지 최종
  src/components/review/Review.tsx
Labels: 🐞 bug

#176 [Fix] 티켓 수 최종
  src/components/details/Reservation.tsx
Labels: 🐞 bug

#177 [Fix] 결제페이지 selector 에러 해결
  src/components/details/Reservation.tsx
  src/hooks/payments/usePaymentWidget.ts
Labels: 🐞 bug

#179 [Refactor] 파트너 메인페이지 ui 수정 및 리드미 수정
  README.md
  public/img/Screenshot1.png
  public/img/Screenshot2.png
  public/img/Screenshot3.png
  public/img/[Project]Travel Port_표지.png
  src/assets/images/partner1.svg
  src/assets/images/partner2.svg
  src/assets/images/partner_arrow.svg
  src/components/main/PartnerMainBanner.tsx
  src/pages/partner/PartnerMain.tsx
Labels: 🧾 page, 💄 style, 📄 docs

#180 [Refactor] 메인 페이지 디자인 수정하기
  src/components/common/layout/Layout.tsx
  src/components/common/layout/headerBar/HeaderBar.tsx
  src/components/common/layout/headerBar/LoginUserHeaderBar.tsx
  src/components/payments/Pay.tsx
  src/pages/user/Main.tsx
Labels: 💄 style, ♻️ refactor

#181 [Refactor] 회원가입 공통요소 컴포넌트화, 예약 거절 시 거절을 확인하는 modal 구현, 기타 오류 수정
  src/apis/reservation.ts
  src/components/auth/SignUp.tsx
  src/components/myPage/modal/RejectReservation.tsx
  src/components/myPage/modal/WriteRejectReason.tsx
  src/components/reservation/ReservedManageCard.tsx
  src/pages/auth/signup/PartnerSignup.tsx
  src/pages/auth/signup/UserSignup.tsx
Labels: 🐞 bug, 🎁 component, ♻️ refactor, ✨ enhancement

#183 [refactor] 카트 가격 추가
  src/apis/cart.ts
  src/components/details/Reservation.tsx
  src/hooks/reactQuery/cart/useCartPostMutation.ts
Labels: ♻️ refactor
