Repository sprint4-part4-team7/TravelPort-49105, pull requests merged in 2024-05, with the labels that each got.

#8 fix: 모듈 에러 해결
  craco.config.js
  package-lock.json
  package.json
  tsconfig.json
Labels: 🐞 bug, ⚙️ setting

#9 [Chore] package 이름 변경(project_setting -> travelport)
  package-lock.json
  package.json
Labels: ⚙️ setting

#10 [Setting] prettier 속성 추가(LF, CRLF auto 설정) 및 package 업데이트
  .prettierrc
  package-lock.json
Labels: ⚙️ setting

#11 [Feat] image 파일 import를 위한 설정 추가
  src/assets/images.d.ts
  tsconfig.json
Labels: ⚙️ setting

#15 [Feat] Location 기능구현
  .eslintrc.json
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/components/common/kakaoMap.tsx
  src/pages/Main.tsx
  src/pages/productRegist/location/Location.tsx
  src/pages/productRegist/location/PostCode.tsx
  tsconfig.json
Labels: 🧾 page, 🐞 bug, 📍 api, ✨ enhancement, ⚙️ setting

#17 [Fix] 이미지 재세팅
  src/index.d.ts
  tsconfig.json
Labels: ⚙️ setting

#22 [Feat] calendar 기초 작업
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/CalendarCustom.tsx
  src/pages/Reservation.tsx
  src/styles/global.css
Labels: ✨ enhancement

#23 [Feat] searchbar 초기 작업
  src/App.tsx
  src/components/common/SearchBar.tsx
  src/pages/List.tsx
Labels: ✨ enhancement

#26 [Feat] Login 페이지 및 공통 컴포넌트(Button, TextBox, InputBox) 초기 구현
  src/assets/images/kakao_login.png
  src/assets/images/kakao_login.svg
  src/components/common/Button.tsx
  src/components/common/InputBox.tsx
  src/components/common/TextBox.tsx
  src/hooks/useOAuthLogin.tsx
  src/pages/Login.tsx
Labels: 🧾 page, 🎁 component, ✨ enhancement

#30 [Chore] 수정된 서치바 헤더에 삽입
  package-lock.json
  package.json
  src/components/common/headerBar/HeaderBar.tsx
  src/components/common/headerBar/UnLoginUserHeaderBar.tsx
Labels: 🎁 component

#38 [Design] figma 시안에 포함된 color 변수 추가
  tailwind.config.js
Labels: 💄 style, ⚙️ setting
